# Image PHP-FPM
FROM php:8.3-fpm

# Installer dépendances + Nginx
RUN apt-get update && apt-get install -y \
    nginx \
    libpng-dev libjpeg62-turbo-dev libfreetype6-dev libpq-dev libonig-dev \
    zip unzip git curl pkg-config \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install pdo pdo_pgsql pdo_mysql mbstring exif pcntl bcmath gd \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Installer Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www

# Copier Laravel
COPY . .

# Installer dépendances Laravel
RUN composer install --no-dev --optimize-autoloader

# Créer dossiers et permissions
RUN mkdir -p /var/www/storage /var/www/bootstrap/cache \
    && chown -R www-data:www-data /var/www \
    && chmod -R 755 /var/www/storage /var/www/bootstrap/cache

# -----------------------------
# Nginx
# -----------------------------

# Supprimer la config par défaut pour éviter doublons
RUN rm -f /etc/nginx/conf.d/default.conf

# Copier config Laravel
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

# PHP-FPM écoute sur TCP
RUN sed -i 's/listen = .*/listen = 127.0.0.1:9000/' /usr/local/etc/php-fpm.d/www.conf

# Exposer port HTTP
EXPOSE 80

# Lancer PHP-FPM + Nginx
CMD sh -c "php-fpm -D && nginx -g 'daemon off;'"
