version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
    volumes:
  
      - ./gestion-immobiliere:/var/www/gestion-immobiliere

  db:
    image: postgres:17
    container_name: laravel_db
    environment:
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: laravel
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
