version: "3.9"

services:
  app:
    build:
      context: ./gestion-immobiliere
      dockerfile: Dockerfile
    container_name: gestion-immobiliere
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./gestion-immobiliere:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"   # accès Laravel via http://localhost:8080
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: postgres:17
    container_name: laravel_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel

networks:
  laravel:

volumes:
  pgdata:
