services:
  - type: web
    name: gestion-immobiliere
    env: docker
    plan: free
    buildCommand: |
      composer install --optimize-autoloader --no-dev
      npm install && npm run build
      php artisan config:clear
      php artisan cache:clear
    startCommand: vendor/bin/heroku-php-apache2 public/
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true